name: basketball_stats_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icone stile iOS
  cupertino_icons: ^1.0.8

  # Pacchetti aggiuntivi
  http: ^0.13.5
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  country_picker: ^2.0.15
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.0
  flutter_svg: ^1.1.6 # Opzionale
  intl: ^0.18.0 # Opzionale
  flutter_spinkit: ^5.1.0 # Opzionale

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting e generazione di codice
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  # Aggiungi risorse qui se necessario
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Rimosso completamente la sezione fonts
